#!/usr/bin/env python3
"""
Convert audio (OGG/WAV) to GBA-compatible 8-bit Signed PCM (.raw and .h)
Specifically tuned for GBA DirectSound A/B channels.
"""

import os
import sys
import subprocess
import struct

def convert_to_gba_pcm(input_path, output_dir, var_name, sample_rate=16000, normalize=True):
    if not os.path.exists(input_path):
        print(f"Error: Input file {input_path} not found!")
        return False

    os.makedirs(output_dir, exist_ok=True)
    raw_path = os.path.join(output_dir, f"{var_name}.raw")
    h_path = os.path.join(output_dir, f"{var_name}_pcm.h")

    # 1. Use ffmpeg to decode to 16-bit mono PCM stream
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-i", input_path,
        "-f", "s16le",
        "-acodec", "pcm_s16le",
        "-ac", "1",
        "-ar", str(sample_rate),
        "pipe:1"
    ]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if res.returncode != 0:
        print(f"FFmpeg error: {res.stderr.decode()}")
        return False

    pcm16 = res.stdout
    num_samples = len(pcm16) // 2
    samples16 = struct.unpack(f"<{num_samples}h", pcm16)

    # 2. Normalize and convert to signed 8-bit (-128 to 127)
    max_val = max(abs(s) for s in samples16) if samples16 else 0
    if normalize and max_val > 0:
        scale = 120.0 / max_val  # Keep headroom to prevent clipping
    else:
        scale = 127.0 / 32768.0

    samples8 = [max(-128, min(127, int(s * scale))) for s in samples16]
    pcm8 = struct.pack(f"{len(samples8)}b", *samples8)

    # 3. Write .raw binary
    with open(raw_path, "wb") as f:
        f.write(pcm8)

    # 4. GBA Timer reload value for Timer 0/1: 65536 - (16777216 / sample_rate)
    timer_cycles = round(16777216.0 / sample_rate)
    timer_reload = 65536 - timer_cycles

    # 5. Write C header file
    with open(h_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by convert_audio.py for GBA DirectSound */\n")
        f.write(f"#ifndef {var_name.upper()}_PCM_H\n")
        f.write(f"#define {var_name.upper()}_PCM_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {var_name.upper()}_SAMPLE_RATE   {sample_rate}\n")
        f.write(f"#define {var_name.upper()}_SAMPLE_COUNT  {len(samples8)}\n")
        f.write(f"#define {var_name.upper()}_TIMER_RELOAD  0x{timer_reload:04X} /* {timer_reload} */\n\n")
        f.write(f"/* 8-bit Signed PCM Data (4-byte aligned for GBA DMA) */\n")
        f.write(f"static const int8_t {var_name}_pcm[{len(samples8)}] __attribute__((aligned(4))) = {{\n")
        
        # Write 16 values per line
        for i in range(0, len(samples8), 16):
            chunk = samples8[i:i+16]
            line_str = ", ".join(f"{v:4d}" for v in chunk)
            comma = "," if i + 16 < len(samples8) else ""
            f.write(f"    {line_str}{comma}\n")
            
        f.write("};\n\n")
        f.write(f"#endif /* {var_name.upper()}_PCM_H */\n")

    duration = len(samples8) / sample_rate
    print(f"Successfully converted {os.path.basename(input_path)}:")
    print(f"  Samples: {len(samples8)} ({duration:.3f} s at {sample_rate} Hz)")
    print(f"  Raw binary: {raw_path} ({len(pcm8)} bytes)")
    print(f"  C Header:   {h_path}")
    print(f"  GBA Timer 0 Reload: 0x{timer_reload:04X} ({timer_reload})")
    return True

if __name__ == "__main__":
    src_base = r"D:\HaxeToolkit\haxe\lib\flixel-demos\3,3,0\Features\FlxFSM\assets"
    out_dir = r"D:\ai\my-llm-test\gemini-3.8-flash\gemini-gba\games\flx-fsm\assets"

    # Convert groundpoundfinish.ogg
    finish_ogg = os.path.join(src_base, "groundpoundfinish.ogg")
    convert_to_gba_pcm(finish_ogg, out_dir, "groundpoundfinish", sample_rate=16000)

    # Convert groundpound.ogg as well
    start_ogg = os.path.join(src_base, "groundpound.ogg")
    convert_to_gba_pcm(start_ogg, out_dir, "groundpound", sample_rate=16000)
